### ISSUE TITLE
Cannot validate Gradle wrapper

### ISSUE THREAD

**Issue by Phua-Lock-Hian** [nus-cs2113-AY2425S2/forum#24]
Hi, my tp pull request is running into an issue with validating the Gradle wrapper as shown below, does anyone know how I can solve this? I found a similar issue on previous year forums and have tried the solution of closing the PR and creating a new one but the problem still persists.

![Image](https://github.com/user-attachments/assets/39fa09b1-965c-43aa-8044-ac69640bb5be)

Here is the link to the problematic PR: https://github.com/AY2425S2-CS2113-T12-2/tp/pull/32

Thanks!

**Comment by randust** [comment]
I have also encountered this too. I tried to pass all local JUnit tests (make all arrows green locally![Image](https://github.com/user-attachments/assets/218245e8-e020-4e2a-8bb9-3bdf22927c3c)), and then it passed the gradle wrapper. I don't know why this is relevant, and not sure if this also works for your case.

**Comment by Phua-Lock-Hian** [comment]
> I have also encountered this too. I tried to pass all local JUnit tests (make all arrows green locally![Image](https://github.com/user-attachments/assets/218245e8-e020-4e2a-8bb9-3bdf22927c3c)), and then it passed the gradle wrapper. I don't know why this is relevant, and not sure if this also works for your case.

Hi, my tests were passing locally already but I still have this issue. Thanks though.

**Comment by Lyam-T** [comment]
Me and my teams also encountered this, I tried close and reopen a new pull request and it works and allow merge somehow. **However** the CI test after merged failed again.
Can we know what exactly is causing this inconsistency testing and how to fix it properly, Thx!
<img width="697" alt="Image" src="https://github.com/user-attachments/assets/b10fb9d8-7893-4039-a9fc-543479183056"/>

**Comment by Lyam-T** [comment]
> Me and my teams also encountered this, I tried close and reopen a new pull request and it works and allow merge somehow. **However** the CI test after merged failed again. Can we know what exactly is causing this inconsistency testing and how to fix it properly, Thx! <img alt="Image" width="697" src="https://private-user-images.githubusercontent.com/121327285/423351340-b10fb9d8-7893-4039-a9fc-543479183056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIyMjIwODksIm5iZiI6MTc0MjIyMTc4OSwicGF0aCI6Ii8xMjEzMjcyODUvNDIzMzUxMzQwLWIxMGZiOWQ4LTc4OTMtNDAzOS1hOWZjLTU0MzQ3OTE4MzA1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxN1QxNDI5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODI2ZTJiNTUyYjBkYjg4NzE4ZDNlZjgzYmNmMzMxMjg2MGNmNzM2MGEwMGZjNmJjNzk5NGFhZmYxZGUyNGFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UIEJbxXs1oJXyoiZHINobglYEzO3roV-YSvxRp4TcYo">

Update
I might have fix the issue, I think for my case it might be that my build.gradle mainClass is incorrectly set. Or it is because the task pass by luck... You can validate it by running locally the gradle test under Tasks/application/run. See if this might help!

**Comment by okkhoy** [comment]
You can try to update this portion of the `gradle.yml` file under` .github/workflows`

```
- name: Validate Gradle Wrapper
  uses: gradle/wrapper-validation-action@v1

- name: Setup JDK 17
  uses: actions/setup-java@v1
  with:
    java-version: '17'
    java-package: jdk+fx
```

with the following

```
- name: Validate Gradle Wrapper
    uses: gradle/actions/wrapper-validation@v3

- name: Setup JDK 17
  uses: actions/setup-java@v4
  with:
    distribution: 'zulu'
    java-version: '17'
    java-package: jdk+fx
```
